version: '3'

services:
    updater:
        tty: true
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/app
        command: bash -c 'cd /app && ./main.go'

